### ISSUE TITLE
Strongly recommend alternative to Apple emojis (Consider SVGs)

### ISSUE THREAD

**Issue by ocdtrekkie** [vikrum/kiddopaint#3]
Someone else suggested this on HN, and I strongly concur.

In addition to the general questions of where Apple emojis will and won't work (they seem to work great, even on Windows, in my Gmail spam box, much to my pain and agony), including the Apple font file would also be problematic from a licensing standpoint.

Ideally, it'd be great to replace the emojis with SVG files, which are extremely lightweight, and can quickly and easily scale to a lot of different sizes. An HN commenter suggested https://commons.wikimedia.org/wiki/Emoji as a source, and https://thenounproject.com/ is a great source for SVG files as well, available in various licenses from Public Domain to Creative Commons.

**Comment by vikrum** [comment]
Is it possible to map the SVG to the base unicode being used elsewhere? I'm eager to find a solution that transitions back to defaulting to unicode on the host system. Here is a screenshot of the problem that was posted to the HN thread: http://snag.gy/4fm3H.jpg

**Comment by ocdtrekkie** [comment]
My honest concern is that using the host system's fonts at any point is begging for bugs to occur. Ideally, you want a web app to be as platform-independent as possible.
